const institutes = [
  "Indian Institute of Technology Bombay (IIT Bombay)",
  "Indian Institute of Technology Delhi (IIT Delhi)",
  "Indian Institute of Technology Kanpur (IIT Kanpur)",
  "Indian Institute of Technology Madras (IIT Madras)",
  "Indian Institute of Technology Kharagpur (IIT Kharagpur)",
  "Indian Institute of Technology Roorkee (IIT Roorkee)",
  "Indian Institute of Technology Guwahati (IIT Guwahati)",
  "Indian Institute of Technology Hyderabad (IIT Hyderabad)",
  "Indian Institute of Technology Patna (IIT Patna)",
  "Indian Institute of Technology Bhubaneswar (IIT Bhubaneswar)",
  "Indian Institute of Technology Gandhinagar (IIT Gandhinagar)",
  "Indian Institute of Technology Jodhpur (IIT Jodhpur)",
  "Indian Institute of Technology Ropar (IIT Ropar)",
  "Indian Institute of Technology Indore (IIT Indore)",
  "Indian Institute of Technology Mandi (IIT Mandi)",
  "Indian Institute of Technology Palakkad (IIT Palakkad)",
  "Indian Institute of Technology Tirupati (IIT Tirupati)",
  "Indian Institute of Technology Bhilai (IIT Bhilai)",
  "Indian Institute of Technology Goa (IIT Goa)",
  "Indian Institute of Technology Jammu (IIT Jammu)",
  "Indian Institute of Technology Dharwad (IIT Dharwad)",
  "National Institute of Technology Tiruchirappalli (NIT Trichy)",
  "National Institute of Technology Surathkal (NIT Surathkal)",
  "National Institute of Technology Warangal (NIT Warangal)",
  "National Institute of Technology Calicut (NIT Calicut)",
  "National Institute of Technology Rourkela (NIT Rourkela)",
  "National Institute of Technology Kurukshetra (NIT Kurukshetra)",
  "National Institute of Technology Durgapur (NIT Durgapur)",
  "National Institute of Technology Silchar (NIT Silchar)",
  "National Institute of Technology Jamshedpur (NIT Jamshedpur)",
  "National Institute of Technology Hamirpur (NIT Hamirpur)",
  "National Institute of Technology Agartala (NIT Agartala)",
  "National Institute of Technology Raipur (NIT Raipur)",
  "National Institute of Technology Patna (NIT Patna)",
  "National Institute of Technology Nagaland (NIT Nagaland)",
  "National Institute of Technology Srinagar (NIT Srinagar)",
  "National Institute of Technology Meghalaya (NIT Meghalaya)",
  "National Institute of Technology Manipur (NIT Manipur)",
  "National Institute of Technology Mizoram (NIT Mizoram)",
  "National Institute of Technology Arunachal Pradesh (NIT Arunachal Pradesh)",
  "Indian Institute of Information Technology Hyderabad (IIIT Hyderabad)",
  "Indian Institute of Information Technology Bangalore (IIIT Bangalore)",
  "Indian Institute of Information Technology Delhi (IIIT Delhi)",
  "Indian Institute of Information Technology Allahabad (IIIT Allahabad)",
  "Indian Institute of Information Technology Gwalior (IIIT Gwalior)",
  "Indian Institute of Information Technology Kancheepuram (IIIT Kancheepuram)",
  "Indian Institute of Information Technology Jabalpur (IIIT Jabalpur)",
  "Indian Institute of Information Technology Kurnool (IIIT Kurnool)",
  "Indian Institute of Information Technology Kota (IIIT Kota)",
  "Indian Institute of Information Technology Lucknow (IIIT Lucknow)",
  "BITS Pilani (Birla Institute of Technology and Science)",
  "Delhi Technological University (DTU)",
  "Vellore Institute of Technology (VIT)",
  "National Institute of Industrial Engineering (NITIE)",
  "Jamia Millia Islamia - Faculty of Engineering and Technology (JMI)",
  "Birla Institute of Technology, Mesra (BIT Mesra)",
  "Motilal Nehru National Institute of Technology Allahabad (MNNIT Allahabad)",
  "College of Engineering, Pune (COEP)",
  "Indian School of Mines, Dhanbad (ISM Dhanbad)",
  "National Institute of Technology Surat (SVNIT Surat)",
  "Punjab Engineering College, Chandigarh (PEC Chandigarh)",
  "Thapar Institute of Engineering and Technology, Patiala (TIET Patiala)",
  "Visvesvaraya National Institute of Technology, Nagpur (VNIT Nagpur)",
  "Bengal Engineering and Science University, Shibpur (BESU Shibpur)",
  "Coimbatore Institute of Technology (CIT)",
  "Manipal Institute of Technology (MIT)",
  "RV College of Engineering (RVCE)",
  "National Institute of Technology Kurukshetra (NIT Kurukshetra)",
  "Indian Institute of Engineering Science and Technology, Shibpur (IIEST Shibpur)",
  "Indian Institute of Information Technology Sri City (IIIT Sri City)",
  "Indian Institute of Information Technology Kottayam (IIIT Kottayam)",
  "Indian Institute of Information Technology Una (IIIT Una)",
  "Indian Institute of Information Technology, Vadodara (IIIT Vadodara)",
  "Indian Institute of Information Technology Pune (IIIT Pune)",
  "Indian Institute of Information Technology, Nagpur (IIIT Nagpur)",
  "Indian Institute of Information Technology Bhagalpur (IIIT Bhagalpur)",
  "Indian Institute of Information Technology Surat (IIIT Surat)",
  "Indian Institute of Information Technology Bhopal (IIIT Bhopal)",
  "Indian Institute of Information Technology, Ranchi (IIIT Ranchi)",
  "Indian Institute of Information Technology, Lucknow (IIIT Lucknow)",
  "Indian Institute of Technology Goa (IIT Goa)",
  "Indian Institute of Technology Jammu (IIT Jammu)",
  "Indian Institute of Technology Dharwad (IIT Dharwad)",
  "Indian Institute of Technology Palakkad (IIT Palakkad)",
  "Indian Institute of Technology Bhilai (IIT Bhilai)",
  "Indian Institute of Technology Tirupati (IIT Tirupati)",
  "Indian Institute of Technology (IIT) Goa",
  "Indian Institute of Technology (IIT) Jammu",
  "Indian Institute of Technology (IIT) Dharwad",
  "Indian Institute of Technology (IIT) Bhilai",
  "Indian Institute of Technology (IIT) Tirupati",
  "National Institute of Technology Sikkim (NIT Sikkim)",
  "National Institute of Technology Manipur (NIT Manipur)",
  "National Institute of Technology Mizoram (NIT Mizoram)",
  "National Institute of Technology Meghalaya (NIT Meghalaya)",
  "National Institute of Technology Nagaland (NIT Nagaland)",
  "National Institute of Technology Arunachal Pradesh (NIT Arunachal Pradesh)",
  "National Institute of Technology Uttarakhand (NIT Uttarakhand)",
  "National Institute of Technology Goa (NIT Goa)",
  "National Institute of Technology Puducherry (NIT Puducherry)",
  "National Institute of Technology Manipur (NIT Manipur)",
  "National Institute of Technology Andhra Pradesh (NIT Andhra Pradesh)",
  "National Institute of Technology Agartala (NIT Agartala)",
  "others",
];

module.exports = institutes;
