const softwareEngineeringSkills = [
  "JavaScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Swift",
  "Kotlin",
  "Go",
  "TypeScript",
  "SQL",
  "HTML/CSS",
  "React",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Ruby on Rails",
  "Spring Boot",
  "ASP.NET",
  "RESTful API Design",
  "GraphQL",
  "DevOps",
  "Containerization (Docker, Kubernetes)",
  "Continuous Integration/Continuous Deployment (CI/CD)",
  "AWS",
  "Azure",
  "Google Cloud Platform (GCP)",
  "Database Management (MySQL, PostgreSQL, MongoDB)",
  "Front-End Development",
  "Back-End Development",
  "Full-Stack Development",
  "Mobile App Development",
  "Web Development",
  "Software Architecture",
  "Software Testing and QA",
  "Machine Learning",
  "Data Science",
  "Big Data",
  "Blockchain Development",
  "Game Development",
  "Cybersecurity",
  "UI/UX Design",
  "Scrum",
  "Version Control (Git)",
  "Android Development",
  "iOS Development",
  "others",
];

module.exports = softwareEngineeringSkills;
